import {test} from 'node:test'
import assert from 'node:assert/strict'
import {MemoryManager} from '../src/manager.js'
import {Usage} from '../src/usage.js'
import {installMvu} from '../src/adapters/mvu.js'
import {skillAdapter} from '../src/adapters/skills.js'
const manager=()=>new MemoryManager({configPath:'/missing-test-config'})
test('native skills use actual Agent scope and never fall back for unknown session',async()=>{const agent={session:{header:{cwd:'/workspace'}}};let seen;const ctx={get:()=>({get:id=>id==='s'?agent:undefined}),skills:{list:async opts=>{seen=opts;return [{name:'test',provider:'fs',path:'/workspace/SKILL.md',description:'x'}]},get:async()=>({name:'test',provider:'fs',path:'/workspace/SKILL.md',content:'body'})}};const adapter=skillAdapter(ctx);const [r]=await adapter.list({scope:{sessionId:'s'}});assert.equal(seen.scope,agent);assert.equal((await adapter.read({id:r.id,scope:{sessionId:'s'}})).content,'body');await assert.rejects(()=>adapter.list({scope:{sessionId:'remote'}}),{code:'AGENT_UNAVAILABLE'})})
test('MVU three ownership states, config errors and deny-by-default scope',async()=>{const m=manager(),usage=new Usage(m);let handler;const service={protocolVersion:1,list:async()=>[],read:async()=>null,validateConfig:()=>{},registerUsage:h=>{handler=h;return()=>{}},observe:()=>()=>{}};const dispose=installMvu(m,service,usage);assert.equal(await handler({id:'mvu:x',managementMode:'native'}),undefined);assert.equal((await handler({id:'mvu:x',managementMode:'managed'})).enabled,false);m.configuration.document={schemaVersion:1,revision:2,presets:{},entries:[{id:'mvu:x',adapterId:'tavern.mvu',type:'mvu-state',whitelist:[],blacklist:[],retrieve:{on:'before_model_request',rule:true,strategy:'read_content'}}]};assert.equal((await handler({id:'mvu:x',managementMode:'managed',on:'before_model_request',scope:{}})).enabled,false);m.configuration.document.entries[0].whitelist=[{global:true}];assert.equal((await handler({id:'mvu:x',managementMode:'managed',on:'before_model_request',scope:{}})).enabled,true);m.configuration.error={code:'INVALID_CONFIG'};assert.equal((await handler({id:'mvu:x',managementMode:'managed'})).enabled,false);dispose();assert.equal(m.adapters.size,0)})
test('unload cancels in-flight read and old generation cannot populate result',async()=>{const m=manager();let resolve;const stop=m.registerAdapter({id:'a',authority:'a',list:async()=>[],read:()=>new Promise(r=>resolve=r)});const job=m.read({adapterId:'a',id:'a:1'});stop();m.registerAdapter({id:'a',authority:'a',list:async()=>[],read:async()=>null});resolve({id:'a:1',type:'text',content:'obsolete'});await assert.rejects(()=>job,{name:'AbortError'})})
test('duplicate identity ownership and invalid JSON are rejected',async()=>{const m=manager();for(const id of ['a','b'])m.registerAdapter({id,authority:id,list:async()=>[{id:'same',type:'text'}],read:async()=>({id:'same',type:'text',content:'x'})});const q=await m.query();assert(q.diagnostics.some(d=>d.code==='OWNERSHIP_CONFLICT'));await assert.rejects(()=>m.read({adapterId:'b',id:'same'}),{code:'OWNERSHIP_CONFLICT'})})
test('source edits preserve CAS and operation identity without local optimistic mutation',async()=>{const m=manager();let content='initial',revision=0;const operations=new Map();m.registerAdapter({id:'a',authority:'a',list:async()=>[{id:'a:1',type:'text'}],read:async()=>({id:'a:1',type:'text',content,revision}),update:async request=>{if(operations.has(request.operationId)){const previous=operations.get(request.operationId);if(previous.content!==request.content)throw Error('IDEMPOTENCY_CONFLICT');return previous}if(request.expectedRevision!==revision)throw Error('REVISION_CONFLICT');content=request.content;revision++;const result={id:'a:1',type:'text',content,revision};operations.set(request.operationId,result);return result}});const request={adapterId:'a',id:'a:1',content:'changed',expectedRevision:0,operationId:'edit'};assert.equal((await m.update(request)).revision,1);assert.equal((await m.update(request)).revision,1);await assert.rejects(()=>m.update({...request,content:'wrong'}),/IDEMPOTENCY_CONFLICT/);await assert.rejects(()=>m.update({...request,operationId:'edit2'}),/REVISION_CONFLICT/);assert.equal((await m.read(request)).content,'changed')})
