import {test} from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,writeFile,readFile} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {MemoryManager} from '../src/manager.js'
import {Usage} from '../src/usage.js'
import {applies,effective,validateDocument} from '../src/config.js'
const doc={schemaVersion:1,revision:1,entries:[{id:'r:1',adapterId:'source',type:'text',whitelist:[{global:true}],blacklist:[{sessionId:'private'}],retrieve:{on:'request',rule:true,strategy:[{operation:'read'}]},preset:'p'}],presets:{p:{retrieve:{rule:{all:[true,{not:false}]}}}}}
async function setup(){const dir=await mkdtemp(join(tmpdir(),'dmm-'));const configPath=join(dir,'config.json');await writeFile(configPath,JSON.stringify(doc));const manager=await new MemoryManager({configPath,journalPath:join(dir,'traces.json')}).init();manager.registerAdapter({id:'source',authority:'test',list:async()=>[{id:'r:1',type:'text'}],read:async()=>({id:'r:1',type:'text',content:'authority-owned',revision:7}),validateConfig:c=>{if(c.type!=='text')throw Error('incompatible type')}});return {manager,dir,configPath}}
test('preset ongoing field precedence, empty lists, identity and blacklist',()=>{let d=validateDocument(doc),c=effective(d,'r:1');assert.equal(c.config.retrieve.on,'request');assert.equal(c.origins['retrieve.rule'],'preset:p');assert.equal(applies(c.config,{sessionId:'private'}),false);assert.equal(applies(c.config,{sessionId:'a'}),true);d.presets.p.whitelist=[];assert.equal(applies(effective(d,'r:1').config,{}),false);d.presets.p.content='replace';assert.throws(()=>validateDocument(d));assert.throws(()=>validateDocument({...doc,entries:[doc.entries[0],doc.entries[0]]}));assert.throws(()=>validateDocument(JSON.parse('{"schemaVersion":1,"revision":1,"entries":[],"presets":{"__proto__":{}}}')))} )
test('failed reload keeps complete previous revision, type errors visible',async()=>{const {manager,configPath}=await setup();await writeFile(configPath,JSON.stringify({...doc,revision:2,presets:{p:{type:'number'}}}));await assert.rejects(()=>manager.reload(),/incompatible/);assert.equal(manager.getConfig('r:1').revision,1);assert.equal((await manager.query()).configError.message,'incompatible type');await writeFile(configPath,JSON.stringify({...doc,revision:2,presets:{p:{blacklist:[]}}}));await manager.reload();assert.equal(manager.getConfig('r:1').revision,2);assert.deepEqual(manager.getConfig('r:1').config.blacklist,[])})
test('trigger executes trusted chain once; preview read only; application separate',async()=>{const {manager}=await setup();const usage=new Usage(manager);let calls=0;usage.registerOperation({id:'read',readOnly:true,run:({value})=>{calls++;return value.content}});const req={id:'r:1',event:{eventId:'e',on:'request',scope:{sessionId:'s'},turn:2,turnKind:'human'}};assert.equal((await usage.trigger({...req,preview:true})).value,'authority-owned');assert.equal(manager.traces.length,0);await usage.trigger(req);assert.equal((await usage.trigger(req)).duplicate,true);assert.equal(calls,2);let row=(await manager.query({scope:{sessionId:'s'},turn:2,turnKind:'human'})).rows[0];assert.equal(row.status,'past');assert.equal(row.applied,false);manager.recordTrace({adapterId:'source',id:'r:1',eventId:'applied',phase:'applied',sessionId:'s',turn:2,turnKind:'human'});row=(await manager.query({scope:{sessionId:'s'},turn:2})).rows[0];assert.equal(row.applied,true);assert.equal((await manager.query({turnKind:'task'})).rows[0].status,'never');await manager.dispose()})
test('running means active execution and unload clears it',async()=>{const {manager}=await setup();manager.recordTrace({adapterId:'source',id:'r:1',eventId:'e',phase:'started',sessionId:'s',requestId:'q'});assert.equal((await manager.query({scope:{sessionId:'s'}})).rows[0].status,'running');manager.recordTrace({adapterId:'source',id:'r:1',eventId:'e',phase:'failed',sessionId:'s',requestId:'q'});assert.equal((await manager.query({scope:{sessionId:'s'}})).rows[0].status,'past');await manager.dispose()})
test('source owns edits and CAS; copying cannot reuse ID; no central content saved',async()=>{const {manager,dir}=await setup();await assert.rejects(()=>manager.update({adapterId:'source',id:'r:1',content:'x',expectedRevision:7,operationId:'op'}),{code:'READ_ONLY'});await manager.dispose();assert.equal(manager.traces.length,0);await assert.rejects(()=>readFile(join(dir,'traces.json')),{code:'ENOENT'})})
test('unknown operations and preview writes fail before starting trace',async()=>{const {manager}=await setup();const usage=new Usage(manager);const req={id:'r:1',event:{eventId:'e',on:'request',scope:{}}};await assert.rejects(()=>usage.trigger(req),{code:'OPERATION_UNAVAILABLE'});usage.registerOperation({id:'read',run:()=>{throw Error('must not run')}});await assert.rejects(()=>usage.trigger({...req,preview:true}),{code:'PREVIEW_WRITE_REFUSED'});assert.equal(manager.traces.length,0)})
test('configuration revisions do not replay a successful event; orphan starts are interrupted after restart',async()=>{
 const {manager,configPath,dir}=await setup(),usage=new Usage(manager);let calls=0
 usage.registerOperation({id:'read',readOnly:true,run:()=>++calls})
 const request={id:'r:1',event:{eventId:'same-intent',on:'request',scope:{sessionId:'s'}}}
 await usage.trigger(request)
 await writeFile(configPath,JSON.stringify({...doc,revision:2}));await manager.reload()
 assert.equal((await usage.trigger(request)).duplicate,true);assert.equal(calls,1)
 manager.recordTrace({id:'r:1',adapterId:'source',eventId:'orphan',requestId:'orphan',sessionId:'s',phase:'started'})
 await manager.dispose()
 const restored=await new MemoryManager({configPath,journalPath:join(dir,'traces.json')}).init()
 assert.equal(restored.active.size,0);assert(restored.traces.find(t=>t.eventId==='orphan').interrupted)
})
