import test from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {MemoryManager} from '../src/manager.js'
import {Usage} from '../src/usage.js'
const combination={type:'text',retrieve:{on:'before_model_request',rule:true,strategy:[{operation:'read'}]}}
const preset=(id='p')=>({id,label:'Read text',adapterIds:['a'],configuration:structuredClone(combination)})
const bundle=(...presets)=>({format:'dsh-memory-manager-presets',version:1,presets})
async function setup(t){const dir=await mkdtemp(join(tmpdir(),'dmm-presets-'));t.after(()=>rm(dir,{recursive:true,force:true}));const path=join(dir,'config.json');await writeFile(path,JSON.stringify({schemaVersion:1,revision:1,entries:[],presets:{}}));const m=await new MemoryManager({configPath:path}).init(),usage=new Usage(m);t.after(()=>m.dispose());let effects=0;usage.registerOperation({id:'read',readOnly:true,run(){effects++;throw Error('must not run')}});m.registerAdapter({id:'a',authority:'test',list(){effects++;return []},read(){effects++},validateConfig(){},optionCatalog:{version:1,types:[{id:'text',label:'Text'}],events:[{id:'before_model_request',label:'Before model',mode:'retrieve'}],strategies:[{id:'read',label:'Read',mode:'retrieve',events:['before_model_request'],value:[{operation:'read'}]}],presets:[{id:'default',label:'Default text',configuration:combination}],modes:{store:{supported:false},retrieve:{supported:true,strategySelection:'chain'}}}});return {m,path,effects:()=>effects}}
test('adapter defaults are available without file writes; explicit edit persists a local override and survives reload',async t=>{const {m,path,effects}=await setup(t),disk=await readFile(path,'utf8'),id='adapter:a:default';assert.equal(m.optionCatalog({adapterId:'a'}).presets.find(p=>p.id===id).origin,'adapter');assert.equal(await readFile(path,'utf8'),disk);const p={...preset(id),label:'Edited default',configuration:{...combination,retrieve:{...combination.retrieve,rule:false}}};const saved=await m.savePresets({bundle:bundle(p),expectedRevision:1,replace:true});assert.equal(saved.revision,2);assert.equal(m.presetLibrary().find(p=>p.id===id).origin,'local');assert.equal(m.optionCatalog({adapterId:'a'}).presets.find(p=>p.id===id).label,'Edited default');await m.reload();assert.equal(m.configuration.document.presets[id].retrieve.rule,false);assert.equal(effects(),0)})
test('invalid fields, modes, events, operations, parameters and missing/disabled adapters reject the entire batch without writing',async t=>{const {m,path}=await setup(t),disk=await readFile(path,'utf8');const invalid=[{...preset(),unknown:1},{...preset(),configuration:{...combination,bogus:true}},{...preset(),configuration:{...combination,retrieve:{...combination.retrieve,bogus:1}}},{...preset(),configuration:{store:{rule:true}}},{...preset(),configuration:{retrieve:{on:'not-supported'}}},{...preset(),configuration:{retrieve:{strategy:[{operation:'unknown'}]}}},{...preset(),configuration:{retrieve:{rule:{condition:{id:'unregistered',extra:1}}}}},{...preset(),adapterIds:['missing']},{...preset(),configuration:{retrieve:{strategy:[{operation:'read',params:{unsupported:1}}]}}},{...preset(),configuration:{retrieve:{strategy:[{operation:'read',extra:true}]}}}];for(const p of invalid){await assert.rejects(m.savePresets({bundle:bundle(preset('good'),p),expectedRevision:1}));assert.equal(await readFile(path,'utf8'),disk);assert.equal(m.configuration.document.revision,1)}m.setAdapterEnabled({id:'a',enabled:false});await assert.rejects(m.savePresets({bundle:bundle(preset()),expectedRevision:1}),{code:'PRESET_ADAPTER_UNAVAILABLE'});assert.equal(await readFile(path,'utf8'),disk)})
test('successful batch round trips names, export format and rules, rejects duplicate IDs and stale/external edits',async t=>{const {m,path}=await setup(t);await m.savePresets({bundle:bundle(preset('one'),preset('two')),expectedRevision:1});const disk=await readFile(path,'utf8');assert.equal(JSON.parse(disk).presets.two.type,'text');await assert.rejects(m.savePresets({bundle:bundle(preset('one')),expectedRevision:2}),{code:'PRESET_EXISTS'});await assert.rejects(m.savePresets({bundle:bundle(preset('three')),expectedRevision:1}),{code:'REVISION_CONFLICT'});assert.equal(await readFile(path,'utf8'),disk);const external=JSON.parse(disk);external.entries.push({id:'other',adapterId:'a'});await writeFile(path,JSON.stringify(external));await assert.rejects(m.savePresets({bundle:bundle(preset('three')),expectedRevision:2}),{code:'REVISION_CONFLICT'});assert.equal(m.configuration.document.revision,2)})
test('new resource can explicitly reference adapter default, materializing only that default at save',async t=>{const {m,path}=await setup(t);await m.saveEntry({id:'a:1',adapterId:'a',entry:{id:'a:1',adapterId:'a',preset:'adapter:a:default'},expectedRevision:1});assert.deepEqual(Object.keys(JSON.parse(await readFile(path,'utf8')).presets),['adapter:a:default']);assert.equal(m.getConfig('a:1').config.retrieve.on,'before_model_request')})
test('unload during adapter preset validation prevents publication',async t=>{const {m,path}=await setup(t),disk=await readFile(path,'utf8');let release,enter;const entered=new Promise(r=>enter=r);m.adapters.get('a').validatePreset=async()=>{enter();await new Promise(r=>release=r)};const saving=m.savePresets({bundle:bundle(preset()),expectedRevision:1});await entered;m.setAdapterEnabled({id:'a',enabled:false});release();await assert.rejects(saving,{code:'VALIDATION_STALE'});assert.equal(await readFile(path,'utf8'),disk)})

test('editing an in-use preset cannot bypass resource validation or broaden its adapter binding',async t=>{const {m,path}=await setup(t);await m.savePresets({bundle:bundle(preset()),expectedRevision:1});await m.saveEntry({id:'a:1',adapterId:'a',entry:{id:'a:1',adapterId:'a',preset:'p'},expectedRevision:2});const disk=await readFile(path,'utf8');m.adapters.get('a').validateConfig=()=>{throw Object.assign(Error('resource-specific denial'),{code:'SOURCE_DENIED'})};await assert.rejects(m.savePresets({bundle:bundle({...preset(),label:'Changed'}),expectedRevision:3,replace:true}),{code:'SOURCE_DENIED'});assert.equal(await readFile(path,'utf8'),disk);assert.equal(m.presetLibrary().find(p=>p.id==='p').label,'Read text')})

test('source-owned imports reject reordered steps and undeclared source parameters atomically',async t=>{const {m,path}=await setup(t),disk=await readFile(path,'utf8');const a=m.adapters.get('a');a.strategyOwner='source';a.optionCatalog.modes.retrieve.strategySelection='fixed';for(const strategy of [[{operation:'read',params:{unknown:true}}],[{operation:'read'},{operation:'read'}],[{operation:'not-declared'}]]){await assert.rejects(m.savePresets({bundle:bundle({...preset(),configuration:{retrieve:{on:'before_model_request',strategy}}}),expectedRevision:1}),{code:'INVALID_PRESET'});assert.equal(await readFile(path,'utf8'),disk)}await m.savePresets({bundle:bundle(preset()),expectedRevision:1});assert.equal(m.configuration.document.revision,2)})
test('registered typed operation parameters reject unknown keys and invalid values',async t=>{const {m,path}=await setup(t),disk=await readFile(path,'utf8');m.usage.registerOperation({id:'typed',readOnly:true,parameters:{type:'object',properties:{count:{type:'integer',minimum:1,maximum:3}},required:['count']},run(){assert.fail('validation must not execute')}});for(const params of [{count:0},{count:2,unknown:1},{}]){await assert.rejects(m.savePresets({bundle:bundle({...preset(),configuration:{retrieve:{strategy:[{operation:'typed',params}]}}}),expectedRevision:1}),{code:'INVALID_PRESET'});assert.equal(await readFile(path,'utf8'),disk)}await m.savePresets({bundle:bundle({...preset(),configuration:{retrieve:{strategy:[{operation:'typed',params:{count:2}}]}}}),expectedRevision:1});assert.equal(m.configuration.document.revision,2)})
