// Installed defaults are resolved without rewriting the user's local file.
export const builtinPresets={
 'builtin:skill-retrieve':{label:'Skill · 请求前读取正文',adapterIds:['dsh.skills'],configuration:{type:'skill',retrieve:{on:'before_model_request',rule:true,strategy:[{operation:'memory.read_content'},{operation:'memory.to_text'}]}}},
 'builtin:mvu-managed':{label:'MVU · 更新与读取',adapterIds:['tavern.mvu'],configuration:{type:'mvu-state',store:{on:'assistant_message_committed',rule:'contains_mvu_update',strategy:[{operation:'parse_mvu_update'},{operation:'validate_update'},{operation:'apply_update'}]},retrieve:{on:'before_model_request',rule:true,strategy:[{operation:'read_content'},{operation:'render_state_and_update_instructions'},{operation:'provide_to_model'}]}}},
 'builtin:mvu-card-interaction':{label:'MVU · 交互更新策略',description:'仅选择来源报告的交互原因；不授予卡片写权限。',adapterIds:['tavern.mvu'],configuration:{type:'mvu-state',store:{on:'card_variable_update',rule:{condition:{id:'mvu_card_write_cause',params:{cause:'user-interaction'}}},strategy:[{operation:'validate_card_update'},{operation:'apply_card_update'}]}}},
 'builtin:worldbook-retrieve':{label:'世界书 · 原生激活与输出',adapterIds:['tavern.world-books'],requiresSourcePolicy:true,configuration:{type:'world-book',retrieve:{on:'before_model_request',rule:true,strategy:[{operation:'worldbook.activate'},{operation:'worldbook.emit'}]}}},
 'builtin:prompt-template-retrieve':{label:'提示词模板 · 展开与输出',adapterIds:['tavern.prompt-templates'],requiresSourcePolicy:true,configuration:{type:'prompt-template',retrieve:{on:'before_model_request',rule:true,strategy:[{operation:'prompt_template.expand'},{operation:'prompt_template.emit'}]}}},
}
export const presetDefinitions=doc=>({...Object.fromEntries(Object.entries(builtinPresets).map(([id,p])=>[id,p.configuration])),...doc.presets})
