import {createElement as h,useEffect,useState,useRef} from 'react'
export const name='dsh-memory-manager'
export const inject=['slots']
const root='/api/dsh-memory-manager'
async function api(path,body,signal){const r=await fetch(root+path,{signal,headers:body?{'Content-Type':'application/json','X-DSH-Memory-Manager':'1'}:undefined,method:body?'POST':'GET',body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error?.message??'Request failed');return data}
const causeLabels={'user-interaction':'用户交互','interval':'定时器','script':'脚本'}
const labels={never:'未触发',past:'曾触发',running:'正在触发'}
const css=`.dmm{font:13px/1.55 var(--dsw-font-family,system-ui);color:var(--dsw-alias-label-primary,#ddd);padding:18px;min-width:0}.dmm h2{font-size:19px;margin:0 0 4px}.dmm p{color:var(--dsw-alias-label-secondary,#aaa);margin:4px 0 16px}.dmm-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.dmm button,.dmm input,.dmm select,.dmm textarea{font:inherit;border:1px solid var(--dsw-alias-border-l2,#444);border-radius:7px;color:inherit;background:var(--dsw-alias-bg-base,#202125);padding:6px 9px}.dmm button{cursor:pointer}.dmm input{width:100px}.dmm textarea{box-sizing:border-box;min-height:170px;width:100%;font-family:monospace}.dmm-row{border:1px solid var(--dsw-alias-border-l2,#444);border-radius:9px;margin:8px 0;overflow:hidden}.dmm-row summary{display:flex;align-items:center;gap:9px;padding:11px;cursor:pointer}.dmm-dot{width:7px;height:7px;border-radius:50%;background:#8b929b}.dmm-row[data-state=past] .dmm-dot{background:#5fae88}.dmm-row[data-state=running] .dmm-dot{background:#e5b64e}.dmm-name{font-weight:600;flex:1}.dmm-meta{font-size:11px;color:var(--dsw-alias-label-secondary,#aaa)}.dmm-content{padding:12px;border-top:1px solid var(--dsw-alias-border-l2,#444)}.dmm pre{white-space:pre-wrap;overflow-wrap:anywhere;font:11px/1.6 monospace;max-height:260px;overflow:auto}.dmm-error{background:#9c363622;color:#dc8585;border:1px solid #9c3636;padding:10px;border-radius:7px;white-space:pre-wrap}.dmm-empty{padding:30px;border:1px dashed #666;border-radius:10px;text-align:center}.dmm-overlay{position:fixed;inset:65px 16px 20px auto;width:min(620px,calc(100vw - 32px));z-index:1000;overflow:auto;border:1px solid var(--dsw-alias-border-l2,#444);border-radius:12px;background:var(--dsw-alias-bg-base,#202125);box-shadow:0 15px 55px #0007}.dmm-close{float:right}.dmm-tag{border-radius:4px;padding:2px 6px;background:#ffffff0b;font-size:11px}`
function Resource({row,sessionId,onChange}){
 const [record,setRecord]=useState(null),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const lifecycle=useRef(null)
 useEffect(()=>{const controller=new AbortController();lifecycle.current=controller;return()=>controller.abort()},[sessionId,row.id,row.adapterId])
 const query=new URLSearchParams({adapterId:row.adapterId,id:row.id,...(sessionId?{sessionId}:{})})
 const load=async()=>{setBusy(true);try{const r=await api('/read?'+query,undefined,lifecycle.current?.signal);setRecord(r);setText(typeof r?.content==='string'?r.content:JSON.stringify(r?.content,null,2));setError('')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const ownership=async()=>{setBusy(true);try{await api('/management',{adapterId:row.adapterId,id:row.id,sessionId,expectedRevision:record.revision,operationId:crypto.randomUUID(),mode:row.managed?'native':'managed'},lifecycle.current?.signal);await load();onChange()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const copy=async()=>{setBusy(true);try{await api('/copy',{adapterId:row.adapterId,id:row.id,sessionId,newId:row.id+'-copy-'+crypto.randomUUID()},lifecycle.current?.signal);onChange()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const save=async()=>{setBusy(true);try{const content=typeof record.content==='string'?text:JSON.parse(text);const r=await api('/update',{adapterId:row.adapterId,id:row.id,sessionId,expectedRevision:record.revision,operationId:crypto.randomUUID(),content},lifecycle.current?.signal);setRecord(r);setError('');onChange()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return h('details',{className:'dmm-row','data-state':row.status},h('summary',null,h('i',{className:'dmm-dot'}),h('span',{className:'dmm-name'},row.name??row.id),h('span',{className:'dmm-tag'},row.applied?'已应用':'无应用证据'),h('span',{className:'dmm-meta'},labels[row.status])),h('div',{className:'dmm-content'},
 row.interrupted&&h('p',null,'先前执行中断，结果未确认'),
 h('div',{className:'dmm-meta'},`${row.adapterId} · ${row.type??'未知类型'} · ${row.missing?'来源不可用':row.authority??''}`),
 h('p',null,row.config?(row.managed?(row.applicable?'已托管 · 当前范围适用':'已托管 · 当前范围不适用'):'来源原生管理 · 配置尚未接管'):'未配置管理规则；来源保持原生行为'),
 h('button',{onClick:load,disabled:busy||row.missing},record?'重新读取':'查看内容'),
 record&&h('div',null,row.missing&&h('p',null,'上次读取的内容；来源当前不可用'),row.capabilities.edit?h('textarea',{'aria-label':'资源内容',value:text,onChange:e=>setText(e.target.value)}):h('pre',null,text),h('div',{className:'dmm-meta'},`版本 ${record.revision??'来源未提供'} · ${row.capabilities.edit?'编辑由来源校验和保存':'来源未提供编辑能力'}`),row.capabilities.edit&&h('button',{onClick:save,disabled:busy},'保存到来源'),row.capabilities.copy&&h('button',{onClick:copy,disabled:busy},'复制为新 ID'),row.capabilities.management&&h('button',{onClick:ownership,disabled:busy},row.managed?'交回来源原生管理':'委托记忆管理')),
 error&&h('div',{className:'dmm-error',role:'alert'},error),
 h('details',null,h('summary',null,'配置及字段来源'),h('pre',null,JSON.stringify({effective:row.config,origins:row.origins},null,2))),
 h('details',{open:true},h('summary',null,`应用记录 · ${row.facts.length}`),row.facts.length?h('pre',null,row.facts.map(f=>`${f.phase}${f.on==='card_variable_update'?' · 卡片变量更新':''}${f.cause?' · '+(causeLabels[f.cause]??f.cause):''} · ${f.turnKind} ${f.turn??'—'} · ${f.requestId??f.eventId}${f.detail||f.reason?' · '+(f.detail??f.reason):''}`).join('\n')):h('p',null,'没有匹配筛选条件的来源触发记录。可用、被读取不代表已提供给模型。'))))
}
function Panel({sessionId,onClose}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[turn,setTurn]=useState(''),[kind,setKind]=useState(''),[status,setStatus]=useState(''),[source,setSource]=useState(''),[version,setVersion]=useState(0)
 useEffect(()=>{const ctrl=new AbortController();let timer;async function load(){try{const q=new URLSearchParams({...(sessionId?{sessionId}:{}),turn,turnKind:kind,status,adapterId:source});setData(await api('/query?'+q,undefined,ctrl.signal));setError('')}catch(e){if(e.name!=='AbortError')setError(e.message)}if(!ctrl.signal.aborted)timer=setTimeout(load,2500)}load();return()=>{ctrl.abort();clearTimeout(timer)}},[sessionId,turn,kind,status,source,version])
 const reload=async()=>{try{await api('/reload',{});setError('')}catch(e){setError(e.message)}setVersion(v=>v+1)}
 return h('section',{className:'dmm','aria-label':sessionId?'会话记忆管理':'全局记忆管理'},onClose&&h('button',{className:'dmm-close',onClick:onClose,'aria-label':'关闭记忆管理'},'×'),h('h2',null,'记忆管理'),h('p',null,sessionId?'当前会话 · 资源使用与应用证据':'全局资源 · 统一查看、配置与来源编辑'),
 h('div',{className:'dmm-toolbar'},h('input',{'aria-label':'轮次筛选',placeholder:'全部轮次',value:turn,onChange:e=>setTurn(e.target.value)}),h('select',{'aria-label':'轮次来源',value:kind,onChange:e=>setKind(e.target.value)},...[['','所有轮次来源'],['human','人类输入'],['task','任务上下文'],['system','系统'],['unknown','未确认']].map(([v,t])=>h('option',{key:v,value:v},t))),h('select',{'aria-label':'触发状态',value:status,onChange:e=>setStatus(e.target.value)},...[['','所有状态'],...Object.entries(labels)].map(([v,t])=>h('option',{key:v,value:v},t))),h('select',{'aria-label':'资源来源',value:source,onChange:e=>setSource(e.target.value)},h('option',{value:''},'所有来源'),...(data?.adapters??[]).map(a=>h('option',{key:a.id,value:a.id},a.name??a.id))),h('button',{onClick:reload},'重载本地配置')),
 error&&h('div',{className:'dmm-error',role:'alert'},error),data?.configError&&h('div',{className:'dmm-error',role:'alert'},`配置未切换；沿用版本 ${data.revision}。${data.configError.message}`),...(data?.diagnostics??[]).map((d,i)=>h('p',{key:i,role:'status'},`${d.adapterId??''}: ${d.message}`)),
 !data?h('p',null,'正在读取来源…'):!data.rows.length?h('div',{className:'dmm-empty'},'没有可见资源。请检查来源是否安装、会话是否加载及筛选条件。'):data.rows.map(row=>h(Resource,{key:row.adapterId+row.id,row,sessionId,onChange:()=>setVersion(v=>v+1)})))
}
function Header({sessionId}){const [open,setOpen]=useState(false);useEffect(()=>setOpen(false),[sessionId]);return h('div',null,h('button',{onClick:()=>setOpen(!open),'aria-label':'记忆管理','aria-expanded':open},'记忆'),open&&h('div',{className:'dmm-overlay',role:'dialog','aria-label':'会话记忆管理'},h(Panel,{key:sessionId,sessionId,onClose:()=>setOpen(false)})))}
export function apply(ctx){ctx.effect(()=>{const style=document.createElement('style');style.textContent=css;document.head.append(style);return()=>style.remove()});ctx.slots.inject('settings.section',()=>ctx.slots.register({name:'settings.section',id:'dsh-memory-manager',label:'记忆管理',order:70},Panel));ctx.slots.inject('conversation.session.header.actions',()=>ctx.slots.register({name:'conversation.session.header.actions',id:'dsh-memory-manager',order:70},Header))}
